# Generated by Django 3.0.6 on 2020-11-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('marital_status', models.IntegerField(choices=[(1, 'Single'), (2, 'Married with DoP'), (3, 'Married without DoP'), (4, 'Widow/Widower')])),
                ('address', models.CharField(max_length=128, null=True)),
                ('current_status', models.IntegerField(choices=[(1, 'Waiting for documents'), (2, 'Sent to the bank'), (3, 'Analysis in progress'), (4, 'Negative decision'), (5, 'Positive decision')])),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_helper.Broker')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.IntegerField(choices=[(1, 'Employment contract'), (2, 'Mandate contract'), (3, 'Small Business')])),
            ],
        ),
        migrations.CreateModel(
            name='SuccessfulLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_helper.Bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_helper.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_helper.Client')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_helper.Occupation')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='income',
            field=models.ManyToManyField(through='loan_helper.ClientOccupation', to='loan_helper.Occupation'),
        ),
        migrations.AddField(
            model_name='client',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_helper.Comment'),
        ),
    ]
