# Generated by Django 3.0.6 on 2020-11-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_helper.Comment'),
        ),
    ]
