# Generated by Django 3.0.6 on 2020-11-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0002_auto_20201125_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='income',
            field=models.ManyToManyField(null=True, through='loan_helper.ClientOccupation', to='loan_helper.Occupation'),
        ),
    ]
