# Generated by Django 3.0.6 on 2020-11-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0003_auto_20201125_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientoccupation',
            name='monthly_income',
            field=models.IntegerField(null=True),
        ),
    ]
