# Generated by Django 3.0.6 on 2020-11-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0004_auto_20201125_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='news',
        ),
        migrations.AddField(
            model_name='comment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_helper.Client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='income',
            field=models.ManyToManyField(through='loan_helper.ClientOccupation', to='loan_helper.Occupation'),
        ),
    ]
