# Generated by Django 3.0.6 on 2020-11-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0005_auto_20201125_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
