# Generated by Django 3.0.6 on 2020-11-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0008_auto_20201126_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfulloan',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
