# Generated by Django 3.0.6 on 2020-11-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0009_successfulloan_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='current_status',
            field=models.IntegerField(choices=[(1, 'New Client'), (2, 'Waiting for documents'), (3, 'Sent to the bank'), (4, 'Offer'), (5, 'Analysis in progress'), (6, 'Negative decision'), (7, 'Positive decision')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='income',
            field=models.ManyToManyField(null=True, through='loan_helper.ClientOccupation', to='loan_helper.Occupation'),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Married with DoP'), (3, 'Married without DoP'), (4, 'Widow/Widower'), (5, 'Divorced')], null=True),
        ),
    ]
