# Generated by Django 3.0.6 on 2020-11-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0010_auto_20201129_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='income',
            field=models.ManyToManyField(through='loan_helper.ClientOccupation', to='loan_helper.Occupation'),
        ),
    ]
