# Generated by Django 3.0.6 on 2020-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0011_auto_20201129_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='occupation',
            field=models.IntegerField(choices=[(1, 'Employment contract'), (2, 'Mandate contract'), (3, 'Small Business'), (4, 'Pension')]),
        ),
    ]
