# Generated by Django 3.0.6 on 2020-12-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0012_auto_20201129_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successfulloan',
            old_name='loan_amount',
            new_name='loan_amount_gross',
        ),
        migrations.AddField(
            model_name='successfulloan',
            name='bank_charge',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successfulloan',
            name='bank_insurance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='successfulloan',
            name='instalment_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successfulloan',
            name='loan_amount_net',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successfulloan',
            name='repayment_term',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
