# Generated by Django 3.0.6 on 2020-12-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0013_auto_20201201_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfulloan',
            name='interest_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
