# Generated by Django 3.0.6 on 2020-12-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0014_successfulloan_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfulloan',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan_helper.Broker'),
            preserve_default=False,
        ),
    ]
