# Generated by Django 3.0.6 on 2020-12-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_helper', '0015_successfulloan_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='current_status',
            field=models.IntegerField(choices=[(1, 'New Client'), (2, 'Waiting for documents'), (3, 'Sent to the bank'), (4, 'Offer'), (5, 'Analysis in progress'), (6, 'Negative decision'), (7, 'Positive decision'), (8, 'Client resign')]),
        ),
    ]
